version: '3.7'
services:
  app:
    build:
      context: "."
      dockerfile: './docker/backend/Dockerfile'
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: './docker/database/Dockerfile'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data: